---
title: "HST 190 Course Project"
author: "Ralph Estanboulieh"
date: "2023-08-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
library(ggbreak) 
library(patchwork)
library(MASS)
```


## Reading-in and processing data
```{r, message=FALSE}
data = read_csv("HST190CourseProject/RUCC_HDR_cleanedup.csv")
data = data %>% mutate(
  RUCA = as.character(RUCC_2013),
  Rurality = if_else(RUCC_2013<4, 'urban', 'rural')
    )

```

## Plotting
```{r, message=FALSE}
ggplot(data=data, aes(x=Data_Value, y=after_stat(density), fill=Rurality)) + 
  geom_histogram(position='identity', alpha=0.6, bins = 60) + 
  xlab('CVD mortality rate') + theme_classic() + theme(legend.position = c(0.75, 0.5))

ggplot(data=data, aes(x=RUCC_2013, y=Data_Value, fill=RUCA)) + 
    geom_jitter(show.legend = FALSE, alpha=0.3) + 
  geom_violin(alpha=0.6, show.legend = FALSE) + 
  geom_point(data = ruca_means, aes(x=RUCC_2013, y=mean, fill=NA), show.legend = F) + 
  theme_classic() + 
  xlab('RUCA score') + ylab('CVD mortality rate') + 
  scale_y_cut(breaks=c(650), which=c(1, 2), scales=c(1,3))

ruca_means = data %>% 
  group_by(RUCC_2013) %>% 
  summarise_at(vars(Data_Value), 
               list(mean=mean, var=var, median=median))

ggplot(data = ruca_means, aes(x=mean, y=var)) + 
  geom_point() + theme_classic() + ylab('variance')

ruca_means = ruca_means %>% pivot_longer(cols=c('mean', 'median'))
ggplot(data=ruca_means, aes(x=RUCC_2013, y=value, color=name)) + 
  geom_line(size=1) +
  geom_point(size=3) +
  xlab('RUCA score') + ylab('CVD mortality rates') + theme_classic() + labs(color='') + theme(legend.position = c(0.1, 0.8))
```

## Testing
```{r}
anova.test = aov(Data_Value ~ RUCA, data = data)
summary(anova.test)
hist(urban.rates$Data_Value)
ks.test.res = ks.test(urban.rates$Data_Value, rural.rates$Data_Value, alternative = "greater")
ks.test.res

```

```{r}
perm.test = function(a, b, n_iters) {
  t = mean(b) - mean(a)
  means = 1:n_iters
  ab = c(a,b)
  for (i in 1:n_iters) {
    perm = sample(ab, length(ab), replace = FALSE)
    a_ = perm[1:length(a)]
    b_ = perm[(length(b)+1):(length(a) + length(b))]
    means[i] = mean(b_) - mean(a_)
  }
  pval = sum(means>t)/n_iters
  return(list(t=t, perms=means, perm.pval=pval))
}

rural.rates = data %>% filter(Rurality=='rural')
urban.rates = data %>% filter(Rurality=='urban')

perm.res = perm.test(urban.rates$Data_Value, rural.rates$Data_Value, 100000)
hist(perm.res$perms)
```

```{r}
data = data %>% mutate(
  count = round(Data_Value/100000 * Population_2010)
)
pois.model = glm(formula = count ~ RUCA + offset(log(Population_2010)), 
                 data = data, family = poisson(link = "log"))
summary(pois.model)
nb.model = glm.nb(formula = count ~ RUCA + offset(log(Population_2010)), data = data)
summary(nb.model)

ggplot(data = data.frame(labels = data$count, 
                         poisson = pois.model$fitted.values, 
                         nb = nb.model$fitted.values), 
       aes(x = labels, y = poisson)) + geom_point() + geom_point(aes(y=nb), color='red') + geom_abline()


```

